---
version: '3'
services:
  tests:
    profiles: ["test"]
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
    command: >
      python -m pytest -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing
    
  backtesting:
    profiles: ["test2"]
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityX.py:/freqtrade/NostalgiaForInfinityX.py"
    command: >
      backtesting
      --datadir user_data/data/${EXCHANGE:-binance}
      --strategy-list NostalgiaForInfinityX
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
  freqtrade:
    profiles: ["prod"]
    #image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityX.py:/freqtrade/NostalgiaForInfinityX.py"
      - "./NostalgiaForInfinityX2.py:/freqtrade/NostalgiaForInfinityX2.py"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/data/binance-usdt-static.json
      --strategy NostalgiaForInfinityX
